---

name: uWSGI
version: 2.0.18
type: wheel
imageset: default-wheel
purepy: false
prebuild:
  all: cp "${SRC_ROOT_0}"/setup.cpyext.py "${SRC_ROOT_0}"/setup.py
apt:
  - libpcre2-dev
yum:
  - pcre-devel
brew:
  - pcre
skip_tests:
  - uwsgidecorators
