---

name: pysam
version: 0.19.1
type: wheel
purepy: false
insert_setuptools: true
apt:
  - libbz2-dev
yum:
  - bzip2-devel
setup_requires:
  - setuptools <58  # setuptools 58 removed support for use_2to3 in setup()
